# Data Analysis
## Data Analysis
### Data Analysis
#### Data Analysis
##### Data Analysis
###### Data Analysis



In [1]:
### python
#### python
##### python
###### python
###### python

### Python
- List
    - []
- Tuple
    - ()
- Strings
    - " " or ' '
- Dict
    - {}
- Sets
    - {}
- Files
- Functions
- Oops

- Welcome to the  world
- **Welcome to the world**
- ***Welcome to the world***


## Python Libraries
- Numpy

- It was data manupulating uses mathematical operations and statiscal analysis

- creating multi dimensional arrays

In [2]:
# create 1d array
import numpy
a = numpy.array([1,2,3,4])
print(a)

[1 2 3 4]


In [5]:
# create 2d array
import numpy as np
a1 = np.array([[1,2,3],[4,5,6]])
print(a1)

[[1 2 3]
 [4 5 6]]


In [6]:
# create 3d array
import numpy as np
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
a2.ndim

2

In [10]:
a.size

4

In [11]:
a1.size

6

In [12]:
a2.size

9

In [14]:
a.size

4

In [15]:
a1.shape

(2, 3)

a2.shape

In [16]:
a[1]

2

In [18]:
a2[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [19]:
a2[1:,2:]

array([[6],
       [9]])

In [20]:
np .random.random()

0.7308414817899044

In [21]:
np.random.randn(1)

array([0.43747697])

In [22]:
np .random.randn(1,10)

array([[-0.37070305, -1.31254796, -1.53832462,  0.08873217,  1.3629132 ,
         0.64887779,  0.52471475, -1.82358794, -0.11667401,  1.2630786 ]])

In [24]:
np .random.randn(1,20,10)

array([[[ 0.59531269, -0.81894627,  2.33145005,  1.72769819,
          1.05949064,  0.24252511, -0.18401978,  0.47973898,
         -0.643617  ,  1.96285839],
        [-0.04472416, -0.20977709, -0.65391688,  1.12214965,
         -1.18168021, -2.30864336,  0.71690769, -2.00344953,
          0.38283874, -1.63968999],
        [ 0.01848284, -1.09353597, -0.7289446 , -0.6042997 ,
          0.02930306, -0.06832515, -2.00699061,  0.48107437,
          0.33468261, -0.18678035],
        [-2.28862869, -0.68642947,  0.34375462,  0.55232929,
          1.14475379,  0.18391911,  0.84856933,  0.95761746,
          1.20874908,  0.72804206],
        [-1.51599439,  0.75660122, -2.12865502, -2.20493543,
          0.59859239,  0.40352946,  0.54406123, -0.51089403,
          1.42806954,  0.24569618],
        [ 0.90410039,  0.39512161,  0.8780354 ,  0.61161065,
          0.19487791,  0.22834976, -0.03557413,  0.42280488,
         -0.73049151,  0.60965991],
        [ 0.16091068, -1.04300899, -0.25322681, -2.0

In [26]:
a=np.random.randint(1,20,15)
print(a)

[10 10  1  7 14  8 17  9 12  4  4  8 17 10 10]
